name: rest_api_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  analyzer: '>=5.2.0 <7.0.0'
  build: ^2.0.0
  exceptions:
    git: https://github.com/mahmood1996/exceptions.git
  rest_api_annotation:
    git: https://github.com/mahmood1996/rest_api_annotation.git
  source_gen: ^1.5.0
  dio: any

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  source_gen_test: ^1.0.6
